#!/bin/bash
#
# change de dossier pour toutes les actions ci-dessous
pushd /config/user-data

# téléchargement du/des fichier(s) iBlocklist
curl -L "http://list.iblocklist.com/?list=ijfqtofzixtwayqovmxn" | gunzip  > Preiblocklist.txt

# AWK : conversion range d'IP d'iblocklist.com en format CIDR
awk -f /config/user-data/range2cidr.awk < Preiblocklist.txt > cidriblocklist.txt

# Ma liste blanche
comm -23 <(sort cidriblocklist.txt) <(sort LocalWhitelist.txt) > preipsetblacklist.txt

# Ma liste noire
cat preipsetblacklist.txt \
        LocalBlacklist.txt > ipsetblacklist.txt

# compteur d'IP
sed -n '$=' ipsetblacklist.txt

# boucle pour intégration des IP au format CIDr dans IPSet
getnetiblockslist() {
cat <<EOF
# Generated by ipset
-N geotmp nethash --hashsize 2048 --probes 4 --resize 20 --maxelem 250000
EOF
cat /config/user-data/ipsetblacklist.txt|egrep '^[0-9]'|egrep '/' |sed -e "s/^/-A geotmp /"
}
getnetiblockslist > /config/user-data/netiblocklist.txt
sudo ipset -! -R < /config/user-data/netiblocklist.txt
sudo ipset -W geotmp P2P
sudo ipset -X geotmp

# compteur d'IP d'ipset
ipset -L P2P | count

# Suppression des fichiers
rm /config/user-data/netiblocklist.txt
rm /config/user-data/ipsetblacklist.txt
rm /config/user-data/preipsetblacklist.txt
rm /config/user-data/cidriblocklist.txt
rm /config/user-data/Preiblocklist.txt
